### PR TITLE
Hungarian translation to Cipherfox

### PR DESCRIPTION
**Pull request by hzsolt94**
Initial Hungarian translations. Needs testing.

### CODE REVIEW

**Comment by gavinhungry** [comment]
Thank you for this!

```
 +<!ENTITY prefs.label      "Beállítások">
 +<!ENTITY prefs.accesskey  "P">
 +<!ENTITY qualys.label     "Qualys SSL Labs szerver teszt">
 +<!ENTITY qualys.accesskey "Q">
 +<!ENTITY copy.label       "Rejtjelezési csomag másolása">
 +<!ENTITY copy.accesskey   "C">
```

Let's update the `accesskey` values, too. Since we're not localizing the name "Qualys," we can leave `qualys.accesskey` alone. I assume that `B` for `prefs.accesskey`, and `R` for `copy.accesskey` are suitable towards the Hungarian translation?

**Comment by hzsolt94** [comment]
Sorry for skipping those. B and R would be suitable, but the convention is e for "Beállítások" and m for "másolás" in hungarian firefox. (I don't really know the reason for this.) Updated the pull request with those.

**Comment by gavinhungry** [comment]
Thanks! If it doesn't change the action of the access key (I don't think that it does), can you make those uppercase, just for uniformity?

**Comment by hzsolt94** [comment]
Shouldn't the access key case match the case they're actually represented in the string? That's why I made them lower case. If it's case-insensitive, I'll be happy to update them.

**Comment by gavinhungry** [comment]
@hzsolt94, I suppose I'm not really sure, but your point makes perfect sense. Thanks again for this!

**Pull request merged**
